### PR TITLE
Breaking Changes for 0.4.0

### PR DESCRIPTION
**Pull request by patrickhulce**
A couple breaking changes necessary to protect against memory attacks, thrown in some long overdue ones as well.

- images larger than 100 megapixels or requiring more than 512MB of memory to decode will throw unless `maxMemoryUsageInMB ` and `maxResolutionInMP` options are increased
- drop decode boolean second argument, options must be an object
- no longer support node versions before 8 LTS
- enable tolerantDecoding by default

### CODE REVIEW

**Comment by eugeneware** [comment]
@patrickhulce I like where this is going - where you can specify a memory limit and override it. Looking great!

**Comment by patrickhulce** [comment]
Thanks @eugeneware! Btw, do you know what's up with the Travis status failing to post on PRs/commits these days? I can't really investigate since I'm not the repo owner.

**Comment by patrickhulce** [comment]
Ah so the Travis issue might be a result of some of the problems they're having (intentionally?) with  "legacy" Travis configurations. We might want to migrate https://travis-ci.com/account/migrate

**Comment by eugeneware** [comment]
LGTM :clap: - Good to merge and deploy @patrickhulce

**Comment by eugeneware** [comment]
@patrickhulce - I had a quick look into the travis-ci stuff. I've kicked off the migration to the new system. It's still not showing up, so not sure how long the migration takes, or if their migration process is broken. If it does work we might need to update the build status badges to go against the .com vs .org links.

**Comment by patrickhulce** [comment]
published [0.4.0](https://github.com/eugeneware/jpeg-js/releases/tag/v0.4.0) 🎉

**Pull request merged**
