### PR TITLE
Fix inverted colors during CMYK decoding

### PR DESCRIPTION
**Pull request by strandedcity**
There appears to be a bug in the CMYK decoder that inverts colors. See https://github.com/eugeneware/jpeg-js/issues/13 and all of the "cmyk" fixtures attached to this pull request.

The change appears to be very small, and I'm unable to find a jpeg where this causes any breaking changes. All existing tests pass, and I've added a number of fixtures to guarantee that rgb and cmyk decoding continues to work for a variety of images that have been processed through adobe, imagemagick, illustrator, and other flows. I also added a test image that displays three different styles of cmyk greyscale. Most of these were "blackened" or "reversed" previously, but all now pass with the change.

Any chance we can get this merged in and released to npm, so that https://github.com/oliver-moran/jimp/issues/88 can be fixed?

One thing to be aware of: I was unable to find a cmyk jpeg that _did_ decode correctly before. So if I'm breaking behavior here, I don't have a way of knowing about it. Do you have example cmyk jpegs that used to work, and don't with this change?

### CODE REVIEW

**Comment by instructaPhil** [comment]
@eugeneware any thoughts on this? I was curious if you had an image that demonstrated correct CMYK decoding without my change?

**Comment by strandedcity** [comment]
@eugeneware any thoughts on this? I was curious if you had an image that demonstrated correct CMYK decoding without my change?

**Comment by eugeneware** [comment]
Hi @strandedcity.

Great work. Thanks for this. I've merged and published as 0.1.2.

Also as I believe in [OPEN Open Source](http://openopensource.org/) I've made you a collaborator of this repo. 

If you give me your npm login I can also give you publish permissions too.

Thanks so much for you contribution.

Cheers,

Eugene

**Comment by eugeneware** [comment]
Also, my actual knowledge of JPEG is rather limited. I've combined two open-source libraries that were unavailable in npm. So please feel free to improve and evolve what we have here!

**Comment by strandedcity** [comment]
Oh, wow! Thank you! Glad I could make a helpful contribution. I'm not really a JPEG decoding expert either, but in combination with jimp I was able to track down this issue by trial and error pretty effectively. I hope I didn't end up breaking something else, but having push access here should let me fix it fast if the Jimp community discovers a problem. I'm trying to put together a library of problematic images, as we've encountered issues deciding pngs also.

My npm login is the same as it is here, strandedcity .

Thanks again! It's a pleasure contributing!

Phil

**Comment by eugeneware** [comment]
@strandedcity - the jimp project looks really cool! 

I've given you npm publish rights, so feel free to push out changes!

**Pull request merged**
