### PR TITLE
chore: add npmignore

### LINKED ISSUE #33: test directory in npm
When looking through node_modules for a project of mine, looking for large packages, I saw that your package has a test directory with 4.3MB of data in it. Maybe you could include a .npmignore or only whitelist the files in lib and index.js with package.json "files"? Because your package could be as small as 60kb or something.

### PR DESCRIPTION
**Pull request by patrickhulce**
closes #33 

only item from .gitignore that is not already ignored by default was `.idea*` (see [docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package), also added the test folder

### CODE REVIEW

**Comment by benwiley4000** [comment]
.npmignore *replaces* .gitignore, so you'll need to include everything from .gitignore unless you want those things to be added to the package.

My typical use case is including a build directory in the npm package, but not the git repository.

**Comment by patrickhulce** [comment]
> .npmignore replaces .gitignore, so you'll need to include everything from .gitignore unless you want those things to be added to the package.

Yes I know hence my comment "only item from .gitignore that is not already ignored by default was .idea*" i.e. that was the only thing in gitignore that needed to be brought over

**Comment by benwiley4000** [comment]
Ah I'm sorry, I think I misunderstood what you meant before. Thanks! :)

**Comment by patrickhulce** [comment]
no worries! :)

**Pull request merged**
